package emag_test;//assert that after the purchase and clicking the cart button, the cart page is displayed
import classPages.*;
//Generated by Selenium IDE

import org.junit.After;


import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

/*
de adaugat in cos un produs (metode getNume, getPret, getPretRedus) TELEVIZOR
comparat pret pagina principala, pret pagina produs, pret cos sa fie identice

extra: comparat preturile de la reduceri (cmplicat) (din xpaths la price(int,decimal,currency))

mai adaugam un produs (metode getNume, getPret, getPretRedus) SISTEM AUDIO
verificam preturile
caldulam subtotalul si vedem daca e corect (metoda getPretTotal)

!!! in console la chrome: xpath: $x('//*[@class="line-item-title main-product-title"]')
                                $x('//*[@class="line-item-title main-product-title" and contains(text(),"audio")]/ancestor::div[@class="line-item main-product"]')
 */




/*

3 teste

1: adauga produs fara reducere in cos si compara preturile si titlurile
2: adauga produs cu reducere in cos si compara preturile si titlurile
3: adauga 2 prod (1 redus, 1 simplu) si compara suma in cos

metoda de stergere a tuturor produselor din cos

SCOP: curatarea si gruparea codului pt citire mai buna
!!!: in clasa buy_fifa.java sa ramana doar numele metodelor din celelalte pageObjects
            scop: readability & encapsulation
*/


/*

la testul cu discount sa verific daca produsul are discount
assert uri pe obiecte de tip Product

mai grupat, facute metode pentru toate actiunile in clasele de webPages pt a ramane cat mai putin si usor de inteles cod in teste

logback
screenshots
 */

public class buy_fifa extends Selenium{

    private static final Logger logger = LoggerFactory.getLogger(buy_fifa.class);

    private Map<String, Object> vars;
    JavascriptExecutor js;

    Home homePage;
    Product productPage;
    Cart cartPage;
    Login loginPage;
    Favorites favoritesPage;
    WebDriverWait wait1;


    /*
    @BeforeClass
    @AfterClass
    pt a rula ceva inainte de a se crea clasa (ex: conex BD)
     */

    @Before
    public void setUp() throws InterruptedException {

        js = (JavascriptExecutor) getDriver();
        vars = new HashMap<String, Object>();

        loginPage = new Login(getDriver());
        homePage = new Home(getDriver());
        productPage = new Product(getDriver());
        cartPage = new Cart(getDriver());
        favoritesPage = new Favorites(getDriver());
        wait1 = new WebDriverWait(getDriver(), 10);

        getDriver().get("https://www.emag.ro/homepage");

        getDriver().findElement(By.id("my_account")).click();

        loginPage.LoginUser("aledobrean@gmail.com", "Mustar20");
    }

    @After
    public void tearDown() throws IOException {
/*
        File screenShot=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
        FileUtils.copyFile(screenShot, new File("C:\\webdrivers\\screen1"));*/
        if (loginPage.isLoggedIn()) {

            getDriver().get("https://www.emag.ro/cart/products?ref=cart");
            int index = cartPage.productList.size() - 1;
            while (index >= 0) {
                cartPage.deleteAProduct(index);
                index--;
            }
        }
    }


    @Test
    public void twoProductsTest() throws NoSuchElementException, WebDriverException, InterruptedException {

        ProductInfo firstProduct=new ProductInfo();
        firstProduct.setTitle(homePage.getFirstProductName());
        firstProduct.setPrice(homePage.getNewPriceFinal("Huawei P20"));
        firstProduct.setOldPrice(homePage.getOldPriceFinal("Huawei P20"));

        homePage.firstProductClick();

        productPage.addToCart();

        productPage.closePurchaseWindow();

        homePage.goToHomePage();

        ProductInfo secondProduct=new ProductInfo();
        secondProduct.setTitle(homePage.getProductName("Samsung Galaxy S8"));
        secondProduct.setPrice(homePage.getNewPriceFinal("Samsung Galaxy S8"));

        homePage.secondProductClick();

        productPage.addToCart();

        productPage.closePurchaseWindow();

        homePage.cartClick();

        ProductInfo cartProduct=new ProductInfo();
        cartProduct.setTitle(cartPage.getName("Huawei P20"));
        cartProduct.setPrice(cartPage.getFinalNewPriceString("Huawei P20"));
        cartProduct.setOldPrice(cartPage.getFinalOldPriceString("Huawei P20"));

        ProductInfo secondCartProduct=new ProductInfo();
        secondCartProduct.setTitle(cartPage.getName("Samsung Galaxy S8"));
        secondCartProduct.setPrice(cartPage.getFinalNewPriceString("Samsung Galaxy S8"));

        /*String sumaProducts = cartPage.getCartSum();

        float sumaTotCalculata = cartPage.getSumOfPrices();
        String suma = Float.toString(sumaTotCalculata);

        logger.info("Compare home page details with cart details");
        assertThat(suma, is(sumaProducts));
        //assertThat(firstProduct, is(cartProduct));*/
    }

    @Test
    public void oneProductDiscountTest() throws InterruptedException {

        String priceHome = homePage.getNewPriceFinal("Huawei P20");
        String priceOldHome = homePage.getOldPriceFinal("Huawei P20");
        String productNameHomePage = homePage.getFirstProductName();

        homePage.firstPhoneDetails.click();

        wait1.until(ExpectedConditions.elementToBeClickable(productPage.closeVoucherFrame));
        productPage.closeVoucherFrame.click();

        WebDriverWait wait1 = new WebDriverWait(getDriver(), 10);
        wait1.until(ExpectedConditions.elementToBeClickable(productPage.addToCart));

        productPage.addToCart();

        wait1.until(ExpectedConditions.visibilityOf(productPage.closePurchaseWindow));

        //close window
        productPage.closePurchaseWindow.click();

        //go to cart
        //Thread.sleep(500);
        wait1.until(ExpectedConditions.visibilityOf(homePage.cartInfo));
        wait1.until(ExpectedConditions.elementToBeClickable(homePage.cartInfo));
        homePage.cartClick();

        String priceCartPage = cartPage.getFinalNewPriceString("Huawei P20");
        String priceOldCartPage = cartPage.getFinalOldPriceString("Huawei P20");
        String productNameCartPage = cartPage.getName("Huawei P20");

        //assertThat(priceCartPage, is(priceHome));
        assertThat(priceOldCartPage, is(priceOldHome));
        assertThat(productNameCartPage, is(productNameHomePage));

    }

    @Test
    public void productWithoutDiscountTest() throws InterruptedException {

        //Thread.sleep(500);

        favoritesPage.clickFavs();
        favoritesPage.clickFavsCategories();

        String favTitle = favoritesPage.getTitle(0);
        String favPrice = favoritesPage.getPrice(0);

        favoritesPage.buyItem(0);
        favoritesPage.clickCart();

        String cartPrice = cartPage.getFinalNewPriceString("Assassin");
        String cartTitle = cartPage.getProductName(0);

        assertThat(favPrice, is(cartPrice));
        assertThat(favTitle, is(cartTitle));
    }

    @Test
    public void Test1(){
         final Logger logger = LoggerFactory.getLogger(buy_fifa.class);
         logger.info("Example log from {}", buy_fifa.class.getSimpleName());
    }
}
